#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: User\Controller
    type: attribute

file_controllers:
    resource:
        path: ../src/File/Controller/
        namespace: File\Controller
    type: attribute

folder_controllers:
    resource:
        path: ..src/Folder/Controller/
        namespace: Folder\Controller
    type: attribute

share_controllers:
    resource:
        path: ..src/Share/Controller/
        namespace: Share\Controller
    type: attribute

api_login_check:
    path: /api/login_check
