#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: User\Controller
    type: attribute

api_login_check:
    path: /api/login_check
